ARG BASE_IMAGE=ubuntu:22.04
FROM ${BASE_IMAGE} AS base

# pass the following environment variables:
# GITHUB_OWNER
# GITHUB_REPOSITORY

ARG CUDA_VERSION=cu121

RUN echo "CUDA_VERSION='${CUDA_VERSION}' TORCH_VERSION='${TORCH_VERSION}'"

ARG ACTION_RUNNER_URL=https://github.com/actions/runner/releases/download/v2.335.1/actions-runner-linux-x64-2.335.1.tar.gz

ARG DEBIAN_FRONTEND=noninteractive

ARG PYTHON="python3.12"

# install python, curl and jq
COPY docker/install_system.sh .
RUN bash install_system.sh && rm install_system.sh

# install actions runner according to the GH guide
WORKDIR /actions-runner
RUN curl -o actions-runner-archive.tar.gz -L $ACTION_RUNNER_URL && tar xzf ./actions-runner-archive.tar.gz

RUN ./bin/installdependencies.sh
COPY docker/runner_entrypoint.sh /actions-runner/entrypoint.sh
RUN chmod -R 777 /actions-runner

RUN mkdir /work && chmod 777 /work

# install mrpro dependencies
# forces rebuild if either the version or the pyproject.toml changes
WORKDIR /

# install mrpro
# forces rebuild on any change in the mrpro directory
COPY . /mrpro/
# Install torch first, pinned, from the correct CUDA-specific index
RUN python -m pip install --no-cache-dir torch --index-url https://download.pytorch.org/whl/${CUDA_VERSION}

# Freeze that exact torch version into a constraints file
RUN python -m pip freeze | grep -i "^torch==" > /tmp/constraints.txt

# Now install everything else, eagerly upgraded, but torch stays pinned
RUN python -m pip install "/mrpro[notebooks]" --no-cache-dir --upgrade --upgrade-strategy "eager" \
    --constraint /tmp/constraints.txt

RUN rm -rf /mrpro

# set user and workdir
USER runner
WORKDIR /actions-runner

ENTRYPOINT ["/actions-runner/entrypoint.sh"]
