ARG BASE_IMAGE=ubuntu:22.04
FROM ${BASE_IMAGE} AS base

ARG DEBIAN_FRONTEND=noninteractive

ARG PYTHON="python3.12"

# install python
COPY docker/install_system.sh .
RUN bash install_system.sh && rm install_system.sh

# install mr2 dependencies
# forces rebuild if either the version or the pyproject.toml changes
COPY docker/install_dependencies.sh pyproject.toml src/mr2/VERSION ./
RUN bash install_dependencies.sh && rm install_dependencies.sh pyproject.toml VERSION

# install mr2
# forces rebuild on any change in the mr2 directory
COPY . /mr2/
RUN python -m pip install  "/mr2[notebooks]" --no-cache-dir --upgrade --upgrade-strategy "eager" && rm -rf /mr2

# set user
USER runner
ENV PATH="/github/home/.local/bin:/home/runner/.local/bin:${PATH}"
