ARG BASE_IMAGE=ubuntu:22.04
FROM ${BASE_IMAGE} AS base

# pass the following environment variables:
# GITHUB_OWNER
# GITHUB_REPOSITORY

ARG CUDA_VERSION=cu121
ARG TORCH_VERSION=2.5.1

ARG ACTION_RUNNER_URL=https://github.com/actions/runner/releases/download/v2.335.1/actions-runner-linux-x64-2.335.1.tar.gz

ARG DEBIAN_FRONTEND=noninteractive

ARG PYTHON="python3.12"

# install python, curl and jq
COPY docker/install_system.sh .
RUN bash install_system.sh && rm install_system.sh

# install actions runner according to the GH guide
WORKDIR /actions-runner
RUN curl -o actions-runner-archive.tar.gz -L $ACTION_RUNNER_URL && tar xzf ./actions-runner-archive.tar.gz

RUN ./bin/installdependencies.sh
COPY docker/runner_entrypoint.sh /actions-runner/entrypoint.sh
RUN chmod -R 777 /actions-runner

RUN mkdir /work && chmod 777 /work

# install mrpro dependencies
# forces rebuild if either the version or the pyproject.toml changes
WORKDIR /

COPY docker/install_dependencies.sh pyproject.toml src/mrpro/VERSION ./

# the 1st argument for the install_dependencies specifies the cuda version for torch
RUN bash install_dependencies.sh ${CUDA_VERSION} && rm install_dependencies.sh pyproject.toml VERSION

# Install torch first, pinned, from the correct CUDA-specific index
RUN python -m pip install --no-cache-dir torch==${TORCH_VERSION} --index-url https://download.pytorch.org/whl/${CUDA_VERSION}

# Pin torch via env var so it also applies inside pip's build-isolation subprocesses
ENV PIP_CONSTRAINT=/tmp/constraints.txt
RUN echo "torch==${TORCH_VERSION}" > /tmp/constraints.txt

RUN cat /tmp/constraints.txt

# install mrpro
# forces rebuild on any change in the mrpro directory
COPY . /mrpro/
RUN python -m pip install "/mrpro[notebooks]" --no-cache-dir --upgrade --upgrade-strategy "eager"
RUN rm -rf /mrpro

# set user and workdir
USER runner
WORKDIR /actions-runner

ENTRYPOINT ["/actions-runner/entrypoint.sh"]
