ARG BASE_IMAGE=ubuntu:22.04
FROM ${BASE_IMAGE} as base

ARG DEBIAN_FRONTEND=noninteractive

ARG PYTHON="python3.11"

# install python and mrpro dependencies
COPY install_mrpro.sh .
RUN bash install_mrpro.sh
RUN rm install_mrpro.sh

# set user
USER runner
