name: Docker

on:
  pull_request:
    paths-ignore:
      - "**.md"
  push:
    branches:
      - main

jobs:
  changes:
    name: Check if Docker files changed
    runs-on: ubuntu-latest
    outputs:
      docker_changed: ${{ steps.filter.outputs.docker }}
    steps:
      - name: Checkout mrpro repo
        uses: actions/checkout@v6

      - name: Check if files in docker or the workflow file have been modified
        uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            docker:
              - 'docker/*'
              - '.github/workflows/docker.yml'

  push_test:
    name: Build test image and push to GHCR
    needs: changes
    if: needs.changes.outputs.docker_changed == 'true' || github.event_name == 'push'
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Packages
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ptb-mr
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          cache-from: type=gha
          cache-to: type=gha,mode=max
          file: docker/Dockerfile
          push: true
          tags: ghcr.io/ptb-mr/mrpro_runner:${{ github.run_id }}

  test:
    name: Test docker container
    needs: [changes, push_test]
    if: needs.changes.outputs.docker_changed == 'true' || github.event_name == 'push'
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/ptb-mr/mrpro_runner:${{ github.run_id }}
      options: --user runner
    steps:
      - name: Checkout repo
        uses: actions/checkout@v6

      - name: Install mrpro and test dependencies
        run: pip install ".[tests]" pytest-github-actions-annotate-failures

      - name: Run PyTest
        run: pytest -n 4 -m "not cuda"

  push_latest:
    name: Pull test image and push with new tag
    needs: [changes, test]
    if: needs.changes.outputs.docker_changed == 'true' || github.event_name == 'push'
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: Login to GitHub Packages
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ptb-mr
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Pull and push Docker image with new tag
        run: |
          docker pull ghcr.io/ptb-mr/mrpro_runner:${{ github.run_id }}
          docker tag ghcr.io/ptb-mr/mrpro_runner:${{ github.run_id }}  ghcr.io/ptb-mr/mrpro_runner:latest
          docker push ghcr.io/ptb-mr/mrpro_runner:latest
