name: Sphinx Docs

on:
  push:
    branches:
      - main
  pull_request:

env:
  IMAGE_NAME: ghcr.io/ptb-mr/mrpro_runner

permissions:
  contents: write

defaults:
  run:
    shell: bash

jobs:
  get_notebooks:
    name: Get list of notebooks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout mrpro repo
        uses: actions/checkout@v6

      - id: set-matrix
        run: |
          echo "notebook_paths=$(find examples/notebooks -type f -name '*.ipynb' | jq -R -s -c 'split("\n")[:-1]')" >> $GITHUB_OUTPUT

      - name: Notebook overview
        run: |
          echo "jupyter-notebooks: ${{ steps.set-matrix.outputs.notebook_paths }}"

    outputs:
      notebook_paths: ${{ steps.set-matrix.outputs.notebook_paths }}

  run_notebook:
    name: Run notebook
    needs: get_notebooks
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write
    container:
      image: ${{ env.IMAGE_NAME }}:latest
      options: --user root
    strategy:
      fail-fast: false
      matrix:
        notebook_path: ${{ fromJson(needs.get_notebooks.outputs.notebook_paths) }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v6

      - name: Install mrpro and dependencies
        run: pip install --upgrade --upgrade-strategy "eager" .[notebooks]

      - name: Notebook name
        run: |
          echo "current jupyter-notebook: ${{ matrix.notebook_path }}"

      - name: Add nb-myst download badge
        env:
          NOTEBOOK: ${{ matrix.notebook_path }}
        run: |
          python - <<'EOF'
          import os
          import nbformat as nbf

          notebook = os.environ["NOTEBOOK"]
          notebook_name = os.path.basename(notebook)
          badge_md = (
              f"[![Download notebook](https://img.shields.io/badge/Download-notebook-blue?logo=jupyter)]"
              f"(path:{notebook_name})"
          )

          nb = nbf.read(open(notebook), as_version=4)
          first_cell = nb["cells"][0] if nb["cells"] else None

          if first_cell and first_cell["cell_type"] == "markdown" and "colab" in first_cell["source"].lower():
              first_cell["source"] += " "
          else:
              nb["cells"].insert(0, nbf.v4.new_markdown_cell())

          nb["cells"][0]["source"] += badge_md
          nbf.write(nb, open(notebook, "w"))
          EOF

      - name: Run notebook
        uses: fzimmermann89/run-notebook@v3
        env:
          RUNNER: ${{ toJson(runner) }}
        with:
          notebook: ${{ matrix.notebook_path }}

      - name: Get artifact names
        id: artifact_names
        run: |
          notebook=${{ matrix.notebook_path }}
          echo "ARTIFACT_NAME=$(basename ${notebook/.ipynb})" >> $GITHUB_OUTPUT
          echo "IPYNB_EXECUTED=$(basename $notebook)" >> $GITHUB_OUTPUT

      - name: Upload notebook
        uses: actions/upload-artifact@v6
        if: always()
        with:
          name: ${{ steps.artifact_names.outputs.ARTIFACT_NAME }}
          path: ${{ github.workspace }}/nb-runner.out/${{ steps.artifact_names.outputs.IPYNB_EXECUTED }}
        env:
          RUNNER: ${{ toJson(runner) }}

  create_documentation:
    name: Build and deploy documentation
    needs: run_notebook
    runs-on: ubuntu-latest
    container:
      image: ${{ env.IMAGE_NAME }}:latest
      options: --user runner
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0 # fetch history for github links
          fetch-tags: true

      - name: Install mrpro and dependencies
        run: pip install .[docs]

      - name: Download executed notebook ipynb files
        id: download
        uses: actions/download-artifact@v7
        with:
          path: ./docs/source/_notebooks/
          merge-multiple: true

      - name: Build docs
        run: |
          sphinx-build -b html ./docs/source ./docs/build/html
          rm -rf ./docs/build/html/.doctrees

      - name: Upload documentation artifact
        id: upload_docs
        uses: actions/upload-artifact@v6
        with:
          name: Documentation
          path: docs/build/html/

      # if one of the above steps fails the "artifact-url" will be an empty string
      - name: Dump documentation info
        if: always()
        run: |
          echo "${{ steps.upload_docs.outputs.artifact-url }}" > artifact_url

      - name: Upload docs-metadata artifact
        if: always()
        uses: actions/upload-artifact@v6
        with:
          name: artifact_url
          path: artifact_url

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}

  # Cancel in-progress runs when a new workflow with the same group name is triggered
  cancel-in-progress: true
