name: Sphinx Docs

on:
  push:
    branches:
      - main
      - documentation
  pull_request:
    branches:
      - main
      - documentation

permissions:
    contents: write

jobs:
  Documentation:
    name: 'Build and deploy Documentation'

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install ".[docs]"

    - name: Build docs
      run: sphinx-build -b html ./docs/source ./docs/build/html

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        publish_branch: github-pages
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs/build/html
