name: Pre-Commit

on:
  pull_request:

jobs:
  pre-commit:
    container:
      image: docker://ckolbptb/mrpro_py311:latest
    steps:
      - uses: actions/checkout@v4
      - uses: pre-commit/action@v3.0.1

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}

  # Cancel in-progress runs when a new workflow with the same group name is triggered
  cancel-in-progress: true
