name: PyTest minimal versions

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test-minimal:
    name: Run Tests for minimal dependencies versions
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/ptb-mr/mrpro_minimal:latest
      options: --user runner
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install MRpro and Dependencies
        # do not update dependencies
        run: pip install .[test]

      - name: Install PyTest GitHub Annotation Plugin
        run: pip install pytest-github-actions-annotate-failures

      - name: Run PyTest and Generate Coverage Report
        # shell bash sets the -o pipefail
        run: |
          pytest -n 4 -m "not cuda" --junitxml=pytest.xml \
          --cov-report=term-missing:skip-covered --cov=mrpro | tee pytest-coverage.txt
        shell: bash

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}

  # Cancel in-progress runs when a new workflow with the same group name is triggered
  cancel-in-progress: true
