name: PyTest minimal versions

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test-minimal:
    name: Run Tests for minimal dependencies versions
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/ptb-mr/mrpro_minimal:latest
      options: --user runner
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install MRpro and Dependencies
        # do not update dependencies
        run: pip install .[tests]

      - name: Run PyTest and log output
        # shell bash sets the -o pipefail
        run: |
          pytest -n 4 -m "not cuda" | tee pytest.log
        shell: bash

      - name: Upload PyTest log
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: pytest-log-minimal
          path: pytest.log

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}

  # Cancel in-progress runs when a new workflow with the same group name is triggered
  cancel-in-progress: true
